### ISSUE TITLE
should provide better error message on signature verify error

### ISSUE THREAD

**Issue by wangshijun** [ArcBlock/mcrypto#7]
When I provided a signature whose byteLength is not 64, should raise an "bad signature length" error

**Comment by tyrchen** [comment]
Shijun found that if the tx is incorrectly signed, it will bail out with:

```
20:45:52.750 [warn]  Failed to check transaction. Error: %FunctionClauseError{args: nil, arity: 3, clauses: nil, function: :ed25519_verify, kind: nil, module: :libdecaf_curve25519}
20:45:52.751 [warn]  Trace:     (libdecaf) /Users/travis/build/ArcBlock/mix-forge-deps/src/deps/libdecaf/src/libdecaf_curve25519.erl:109: :libdecaf_curve25519.ed25519_verify(<<211, 29, 223, 113, 167, 189, 125, 167, 56, 227, 134, 154, 213, 253, 61, 107, 77, 218, 223, 215, 250, 225, 238, 221, 127, 111, 52, 231, 79, 120, 243, 222, 223, 219, 126, 181, 107, 111, 124, 113, 237, 56, 123, 214, 188, 239, 126, 91, 221, 191, ...>>, <<240, 69, 115, 186, 86, 29, 106, 100, 254, 16, 238, 146, 147, 32, 180, 250, 5, 174, 130, 242, 134, 46, 55, 241, 6, 215, 70, 187, 246, 28, 18, 10>>, <<255, 21, 96, 74, 217, 124, 86, 219, 78, 145, 7, 133, 234, 107, 208, 103, 254, 196, 226, 8, 30, 55, 228, 136, 244, 234, 66, 242, 34, 21, 78, 175>>)
   (forge_tx) lib/forge_tx/common_pipes/verify_signature.ex:16: Forge.Pipe.VerifySignature.call/2
   (forge_tx) /Users/tchen/projects/arcblock/forge/deps/forge_pipe/lib/forge_pipe/pipeline_builder.ex:38: ForgeTx.PrePipeline.Check.pipe_builder_call/2
   (forge_tx) lib/forge_tx/helper.ex:55: ForgeTx.Helper.pre_check/2
   (forge) lib/forge/abci/server.ex:416: Forge.Abci.Server.handle_call/3
   (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
   (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
   (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

{:error, :internal}
```

I found that this is because the signature is 97 bytes, not 64. We shall give better error message on this.
